# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# Fastfile

#?
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
   xcodebuild(
	   project:" MyNotes.xcodeproj",
	   scheme: "MyNotes",
	   configuration: "Debug",
	   clean: options[:clean],
	   build: true,
	   destination: "generic/platform=iOS",
	   build_settings: {
	    "CODE_SIGNING_REQUIRED" => "NO",
	    "CODE_SIGN_IDENTITY" => ""
         }
      )
  end
end


# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#      gym(
#         # Specify the project or workspace file name
#         project: "MyNotes.xcodeproj",
#         # Set the scheme to build
#         scheme: "MyNotes",
#         # Set the output directory for the build
#         output_directory: "./builds",
#         # Set the name for the output .ipa file
#         output_name: "MyNotes.ipa"
#        )
#          puts("hi zain")
#   end
# end
# Fastfile

# default_platform(:ios)

# # Define lane for creating a build
# lane :build do
#   # Use gym action to create a build
#   gym(
#     # Specify the project or workspace file name
#     project: "MyNotes.xcodeproj",
#     # Set the scheme to build
#     scheme: "MyNotes",
#     # Set the output directory for the build
#     output_directory: "./builds",
#     # Set the name for the output .ipa file
#     output_name: "MyNotes.ipa"
#   )
# end

