# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# Fastfile

#?
default_platform(:ios)
platform :ios do
      desc “Install pod dependencies”
#       lane :install_pods do
#          cocoapods(
#              podfile: "/Users/ec2-user/.jenkins/workspace/SampleProject",
#              use_bundle_exec: false)
# end
      
#       desc "Incrementing Build Number"
#       lane :increment_build do
#            current_build_number = latest_testflight_build_number(version: "1.0")
#            increment_build_number(
#            build_number: current_build_number + 1
#            )
#       end
      desc “Archive and Build IPA”
      lane :build_ipa do
       install_pods
       increment_build
          gym(
             workspace: "SampleProject",
             scheme: "MyNotes",
             output_directory: "/Users/ec2-user/.jenkins/workspace/SampleProject",
             output_name: "MyNotes",
             export_method: “app-store”,
             include_bitcode: false,
             clean: true)
       end
end
# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
# lane :custom_lane do |options|
# 	   xcodebuild(
# 		   project:" MyNotes.xcodeproj",
# 		   scheme: "MyNotes",
# 		   configuration: "Debug",
# 		   clean: options[:clean] || false,
# 		   build: true,
# 		   destination: "generic/platform=iOS",
# 		   build_settings: {
# 		    "CODE_SIGNING_REQUIRED" => "NO",
# 		    "CODE_SIGN_IDENTITY" => ""
# 		 }
# 	      )
#   end
# end


# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#      gym(
#         # Specify the project or workspace file name
#         project: "MyNotes.xcodeproj",
#         # Set the scheme to build
#         scheme: "MyNotes",
#         # Set the output directory for the build
#         output_directory: "./builds",
#         # Set the name for the output .ipa file
#         output_name: "MyNotes.ipa"
#        )
#          puts("hi zain")
#   end
# end
# Fastfile

# default_platform(:ios)

# # Define lane for creating a build
# lane :build do
#   # Use gym action to create a build
#   gym(
#     # Specify the project or workspace file name
#     project: "MyNotes.xcodeproj",
#     # Set the scheme to build
#     scheme: "MyNotes",
#     # Set the output directory for the build
#     output_directory: "./builds",
#     # Set the name for the output .ipa file
#     output_name: "MyNotes.ipa"
#   )
# end

